### ISSUE TITLE
Decide what questions the guide should go through

### ISSUE THREAD

**Issue by bence-toth** [impact-roasters/coffee-guide#6]
Let me try to distill the decision logic:

### 1. What is your preferred coffee profile?

- Clean (light body)
- Rich (full body)

### 2. Which one would you go for?
- Sweet
- Acidic
- Round (only if Clean was selected before)

### 3. Which of these characteristics would you like to experience in your cup of coffee? 
The options here depend on previous selections

It's based on the `tastingProfile` members of the `coffee.js` object

### 4. What roast level do you enjoy?

- Dark
- Medium
- Light

**Comment by Linaimpact** [comment]
1. What is your preferred coffee profile?

- Clean (light body)  Note for us (all 3:sweet, acidic, round)
- Rich (full body) Note for us (only 2: sweet and acidic)

 2. Which one would you go for?

- Sweet 
- Acidic 
- Round

3. Which of these characteristics would you like to experience in your cup of coffee? (interactive);4. 

Chocolate, Citrus, Nougat, Nutty, Forest Berries, Spicy, Fruity, Floral
